java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:325)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.Object android.util.Pair.first' on a null object reference
	at com.ichi2.libanki.Note._fieldOrd(Note.java:200)
	at com.ichi2.libanki.Note.setItem(Note.java:210)
	at com.ichi2.libanki.AnkiPackageExporter._addDummyCollection(AnkiPackageExporter.java:447)
	at com.ichi2.libanki.AnkiPackageExporter.exportVerbatim(AnkiPackageExporter.java:359)
	at com.ichi2.libanki.AnkiPackageExporter.exportInto(AnkiPackageExporter.java:341)
	at com.ichi2.async.CollectionTask.doInBackgroundExportApkg(CollectionTask.java:1223)
	at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:301)
	at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:73)
	at android.os.AsyncTask$2.call(AsyncTask.java:305)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more
